### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by ja0n** [NatalJS/nataljs#2]
here are two ideas.
the third idea would be to replace the second star with the first one
![logoestrela](https://cloud.githubusercontent.com/assets/8407904/9705337/e3e8d6b6-5497-11e5-8a1d-cba30592944c.png)
![logoreismagos](https://cloud.githubusercontent.com/assets/8407904/9705338/e3ead3b2-5497-11e5-8c68-05ec884b8637.png)

**Comment by StefanYohansson** [comment]
surely, the first star. :+1: @andCoffeeCode what do you think ?

~ (I thought something like wise men riding a rhino :hamster:)

**Comment by ghost** [comment]
pretty cute +1

**Comment by StefanYohansson** [comment]
Possible logo.

@netoguimaraes @ja0n @andCoffeeCode 

![possible-logo](https://cloud.githubusercontent.com/assets/1783252/25485142/2a8e5456-2b33-11e7-9cff-83ff332adc6b.png)

**Comment by batoreh** [comment]
I LOVE IT!!!!111!

**Comment by diasbruno** [comment]
ping @StefanYohansson @netoguimaraes @ja0n

**Comment by StefanYohansson** [comment]
I'll use latest logo. closing logo proposal.

**Comment by Mazuh** [comment]
sugoi

**Comment by jhonnymichel** [comment]
who is ghost

**Comment by StefanYohansson** [comment]
old bruno dias account

**Comment by diasbruno** [comment]
I'm a ghost.

**Comment by batoreh** [comment]
andcoffeandcode
